export const ICON_MAPPING = {
  // Brand Technology Logos (Simple Icons)
  react: { slug: 'simple-icons:react', name: 'React', keywords: ['react', 'native', 'jsx', 'tsx'] },
  vue: { slug: 'simple-icons:vue', name: 'Vue.js', keywords: ['vue', 'vuejs'] },
  angular: { slug: 'simple-icons:angular', name: 'Angular', keywords: ['angular', 'angularjs'] },
  svelte: { slug: 'simple-icons:svelte', name: 'Svelte', keywords: ['svelte'] },
  nodedotjs: { slug: 'simple-icons:nodedotjs', name: 'Node.js', keywords: ['node', 'nodejs', 'nodedotjs'] },
  express: { slug: 'simple-icons:express', name: 'Express', keywords: ['express', 'expressjs'] },
  nextdotjs: { slug: 'simple-icons:nextdotjs', name: 'Next.js', keywords: ['next', 'nextjs', 'nextdotjs'] },
  nuxtdotjs: { slug: 'simple-icons:nuxtdotjs', name: 'Nuxt.js', keywords: ['nuxt', 'nuxtjs', 'nuxtdotjs'] },
  mongodb: { slug: 'simple-icons:mongodb', name: 'MongoDB', keywords: ['mongo', 'mongodb'] },
  postgresql: { slug: 'simple-icons:postgresql', name: 'PostgreSQL', keywords: ['postgres', 'postgresql', 'sql', 'psql'] },
  mysql: { slug: 'simple-icons:mysql', name: 'MySQL', keywords: ['mysql'] },
  redis: { slug: 'simple-icons:redis', name: 'Redis', keywords: ['redis'] },
  firebase: { slug: 'simple-icons:firebase', name: 'Firebase', keywords: ['firebase'] },
  supabase: { slug: 'simple-icons:supabase', name: 'Supabase', keywords: ['supabase'] },
  docker: { slug: 'simple-icons:docker', name: 'Docker', keywords: ['docker'] },
  kubernetes: { slug: 'simple-icons:kubernetes', name: 'Kubernetes', keywords: ['k8s', 'kube', 'kubernetes'] },
  aws: { slug: 'simple-icons:amazonwebservices', name: 'AWS', keywords: ['aws', 'amazon', 's3', 'ec2'] },
  googlecloud: { slug: 'simple-icons:googlecloud', name: 'Google Cloud', keywords: ['gcp', 'google cloud', 'googlecloud'] },
  microsoftazure: { slug: 'simple-icons:microsoftazure', name: 'Azure', keywords: ['azure', 'microsoftazure', 'microsoft azure'] },
  python: { slug: 'simple-icons:python', name: 'Python', keywords: ['python', 'py'] },
  javascript: { slug: 'simple-icons:javascript', name: 'JavaScript', keywords: ['javascript', 'js'] },
  typescript: { slug: 'simple-icons:typescript', name: 'TypeScript', keywords: ['typescript', 'ts'] },
  html5: { slug: 'simple-icons:html5', name: 'HTML5', keywords: ['html', 'html5'] },
  css3: { slug: 'simple-icons:css3', name: 'CSS3', keywords: ['css', 'css3'] },
  tailwindcss: { slug: 'simple-icons:tailwindcss', name: 'Tailwind CSS', keywords: ['tailwind', 'tailwindcss'] },
  bootstrap: { slug: 'simple-icons:bootstrap', name: 'Bootstrap', keywords: ['bootstrap'] },
  sass: { slug: 'simple-icons:sass', name: 'Sass', keywords: ['sass', 'scss'] },
  go: { slug: 'simple-icons:go', name: 'Go', keywords: ['go', 'golang'] },
  rust: { slug: 'simple-icons:rust', name: 'Rust', keywords: ['rust'] },
  cplusplus: { slug: 'simple-icons:cplusplus', name: 'C++', keywords: ['c++', 'cpp', 'cplusplus'] },
  csharp: { slug: 'simple-icons:csharp', name: 'C#', keywords: ['c#', 'csharp'] },
  java: { slug: 'simple-icons:java', name: 'Java', keywords: ['java'] },
  php: { slug: 'simple-icons:php', name: 'PHP', keywords: ['php'] },
  ruby: { slug: 'simple-icons:ruby', name: 'Ruby', keywords: ['ruby'] },
  rubyonrails: { slug: 'simple-icons:rubyonrails', name: 'Ruby on Rails', keywords: ['rails', 'rubyonrails'] },
  swift: { slug: 'simple-icons:swift', name: 'Swift', keywords: ['swift'] },
  kotlin: { slug: 'simple-icons:kotlin', name: 'Kotlin', keywords: ['kotlin'] },
  flutter: { slug: 'simple-icons:flutter', name: 'Flutter', keywords: ['flutter'] },
  git: { slug: 'simple-icons:git', name: 'Git', keywords: ['git'] },
  github: { slug: 'simple-icons:github', name: 'GitHub', keywords: ['github'] },
  gitlab: { slug: 'simple-icons:gitlab', name: 'GitLab', keywords: ['gitlab'] },
  bitbucket: { slug: 'simple-icons:bitbucket', name: 'Bitbucket', keywords: ['bitbucket'] },
  jenkins: { slug: 'simple-icons:jenkins', name: 'Jenkins', keywords: ['jenkins'] },
  figma: { slug: 'simple-icons:figma', name: 'Figma', keywords: ['figma'] },
  vercel: { slug: 'simple-icons:vercel', name: 'Vercel', keywords: ['vercel'] },
  netlify: { slug: 'simple-icons:netlify', name: 'Netlify', keywords: ['netlify'] },
  heroku: { slug: 'simple-icons:heroku', name: 'Heroku', keywords: ['heroku'] },
  digitalocean: { slug: 'simple-icons:digitalocean', name: 'DigitalOcean', keywords: ['digitalocean', 'do'] },
  sqlite: { slug: 'simple-icons:sqlite', name: 'SQLite', keywords: ['sqlite'] },
  graphql: { slug: 'simple-icons:graphql', name: 'GraphQL', keywords: ['graphql', 'gql'] },
  prisma: { slug: 'simple-icons:prisma', name: 'Prisma', keywords: ['prisma'] },
  sequelize: { slug: 'simple-icons:sequelize', name: 'Sequelize', keywords: ['sequelize'] },
  mongoose: { slug: 'simple-icons:mongoose', name: 'Mongoose', keywords: ['mongoose'] },
  django: { slug: 'simple-icons:django', name: 'Django', keywords: ['django'] },
  flask: { slug: 'simple-icons:flask', name: 'Flask', keywords: ['flask'] },
  fastify: { slug: 'simple-icons:fastify', name: 'Fastify', keywords: ['fastify'] },
  fastapi: { slug: 'simple-icons:fastapi', name: 'FastAPI', keywords: ['fastapi'] },
  spring: { slug: 'simple-icons:spring', name: 'Spring', keywords: ['spring', 'springboot'] },
  laravel: { slug: 'simple-icons:laravel', name: 'Laravel', keywords: ['laravel'] },
  nestjs: { slug: 'simple-icons:nestjs', name: 'NestJS', keywords: ['nestjs'] },
  webpack: { slug: 'simple-icons:webpack', name: 'Webpack', keywords: ['webpack'] },
  vite: { slug: 'simple-icons:vite', name: 'Vite', keywords: ['vite'] },
  eslint: { slug: 'simple-icons:eslint', name: 'ESLint', keywords: ['eslint'] },
  prettier: { slug: 'simple-icons:prettier', name: 'Prettier', keywords: ['prettier'] },
  jest: { slug: 'simple-icons:jest', name: 'Jest', keywords: ['jest'] },
  cypress: { slug: 'simple-icons:cypress', name: 'Cypress', keywords: ['cypress'] },
  playwright: { slug: 'simple-icons:playwright', name: 'Playwright', keywords: ['playwright'] },
  redux: { slug: 'simple-icons:redux', name: 'Redux', keywords: ['redux'] },
  webassembly: { slug: 'simple-icons:webassembly', name: 'WebAssembly', keywords: ['wasm', 'webassembly'] },
  linux: { slug: 'simple-icons:linux', name: 'Linux', keywords: ['linux'] },
  ubuntu: { slug: 'simple-icons:ubuntu', name: 'Ubuntu', keywords: ['ubuntu'] },
  android: { slug: 'simple-icons:android', name: 'Android', keywords: ['android'] },
  apple: { slug: 'simple-icons:apple', name: 'Apple', keywords: ['ios', 'apple', 'macos', 'swiftui', 'ipad'] },
  windows: { slug: 'simple-icons:windows', name: 'Windows', keywords: ['windows', 'win32'] },
  markdown: { slug: 'simple-icons:markdown', name: 'Markdown', keywords: ['markdown', 'md'] },
  jupyter: { slug: 'simple-icons:jupyter', name: 'Jupyter', keywords: ['jupyter', 'notebook'] },
  pytorch: { slug: 'simple-icons:pytorch', name: 'PyTorch', keywords: ['pytorch', 'torch'] },
  tensorflow: { slug: 'simple-icons:tensorflow', name: 'TensorFlow', keywords: ['tensorflow', 'tf'] },
  keras: { slug: 'simple-icons:keras', name: 'Keras', keywords: ['keras'] },
  opencv: { slug: 'simple-icons:opencv', name: 'OpenCV', keywords: ['opencv'] },
  pandas: { slug: 'simple-icons:pandas', name: 'pandas', keywords: ['pandas'] },
  numpy: { slug: 'simple-icons:numpy', name: 'NumPy', keywords: ['numpy'] },
  nginx: { slug: 'simple-icons:nginx', name: 'Nginx', keywords: ['nginx'] },
  cloudflare: { slug: 'simple-icons:cloudflare', name: 'Cloudflare', keywords: ['cloudflare'] },
  postman: { slug: 'simple-icons:postman', name: 'Postman', keywords: ['postman'] },
  swagger: { slug: 'simple-icons:swagger', name: 'Swagger', keywords: ['swagger', 'openapi'] },
  terraform: { slug: 'simple-icons:terraform', name: 'Terraform', keywords: ['terraform'] },
  prometheus: { slug: 'simple-icons:prometheus', name: 'Prometheus', keywords: ['prometheus'] },
  grafana: { slug: 'simple-icons:grafana', name: 'Grafana', keywords: ['grafana'] },
  elasticsearch: { slug: 'simple-icons:elasticsearch', name: 'Elasticsearch', keywords: ['elasticsearch', 'elk'] },
  datadog: { slug: 'simple-icons:datadog', name: 'Datadog', keywords: ['datadog'] },
  sentry: { slug: 'simple-icons:sentry', name: 'Sentry', keywords: ['sentry'] },
  jira: { slug: 'simple-icons:jira', name: 'Jira', keywords: ['jira'] },
  slack: { slug: 'simple-icons:slack', name: 'Slack', keywords: ['slack'] },
  discord: { slug: 'simple-icons:discord', name: 'Discord', keywords: ['discord'] },
  notion: { slug: 'simple-icons:notion', name: 'Notion', keywords: ['notion'] },
  obsidian: { slug: 'simple-icons:obsidian', name: 'Obsidian', keywords: ['obsidian'] },
  wordpress: { slug: 'simple-icons:wordpress', name: 'WordPress', keywords: ['wordpress'] },
  shopify: { slug: 'simple-icons:shopify', name: 'Shopify', keywords: ['shopify'] },
  stripe: { slug: 'simple-icons:stripe', name: 'Stripe', keywords: ['stripe'] },
  paypal: { slug: 'simple-icons:paypal', name: 'PayPal', keywords: ['paypal'] },
  auth0: { slug: 'simple-icons:auth0', name: 'Auth0', keywords: ['auth0'] },
  clerk: { slug: 'simple-icons:clerk', name: 'Clerk', keywords: ['clerk'] },
  openai: { slug: 'simple-icons:openai', name: 'OpenAI', keywords: ['openai', 'gpt', 'llm'] },
  anthropic: { slug: 'simple-icons:anthropic', name: 'Anthropic', keywords: ['anthropic', 'claude'] },
  huggingface: { slug: 'simple-icons:huggingface', name: 'Hugging Face', keywords: ['huggingface', 'hf'] },
  langchain: { slug: 'simple-icons:langchain', name: 'LangChain', keywords: ['langchain'] },
  pinecone: { slug: 'simple-icons:pinecone', name: 'Pinecone', keywords: ['pinecone'] },

  // General Developer Concepts (Lucide Icons)
  systemdesign: { slug: 'lucide:git-network', name: 'System Design', keywords: ['system design', 'system-design', 'architecture', 'network', 'distributed'] },
  interviewprep: { slug: 'lucide:brain-circuit', name: 'Interview Prep', keywords: ['interview', 'prep', 'career', 'job', 'hr', 'practice'] },
  ai: { slug: 'lucide:sparkles', name: 'AI / Machine Learning', keywords: ['ai', 'artificial intelligence', 'ml', 'neural', 'deep learning'] },
  personalnotes: { slug: 'lucide:notebook', name: 'Personal Notes', keywords: ['notes', 'personal', 'diary', 'journal', 'book', 'writing', 'todo'] },
  database: { slug: 'lucide:database', name: 'Database', keywords: ['database', 'db', 'sql', 'nosql', 'storage'] },
  api: { slug: 'lucide:api', name: 'API / Integration', keywords: ['api', 'endpoints', 'rest', 'restful', 'webhook'] },
  testing: { slug: 'lucide:test-tube', name: 'Testing', keywords: ['test', 'testing', 'unit test', 'qa', 'coverage'] },
  security: { slug: 'lucide:shield-check', name: 'Security', keywords: ['security', 'auth', 'cyber', 'cryptography', 'shield'] },
  devops: { slug: 'lucide:infinity', name: 'DevOps / CI-CD', keywords: ['devops', 'cicd', 'pipeline', 'deployment', 'workflow'] }
};

export const getIconKeyByName = (name) => {
  if (!name) return 'lucide:folder';
  const lowerName = name.toLowerCase().trim();
  
  // Find first matching tool based on keywords
  for (const [key, config] of Object.entries(ICON_MAPPING)) {
    if (config.keywords.some(kw => lowerName.includes(kw))) {
      return config.slug;
    }
  }
  return 'lucide:folder';
};
